### PR TITLE
Finish the project structure and some APIs

### PR DESCRIPTION
**Pull request by Luorinz**
1. Solve all existed bugs
2. Add some utils for the project(Enum, dto objects, etc)
3. Add some tests for UserDao and UserService
4. Add comments for most of the class

### CODE REVIEW

**Review by Pierre-Alexandre35 — DISMISSED** [review]

**Review by Pierre-Alexandre35 — DISMISSED** [review]

**Review by shwetamandavgane — DISMISSED** [review]

**Comment by patelvp** [comment]
Going to add few commits for test setup

**Comment by patelvp** [comment]
Tests probably fail because you are not clearing the database after test run

**Comment by patelvp** [comment]
I would recommend writing a tear down block to wipe out the database

**Comment by patelvp** [comment]
Also can you explore using in memory database? It is much faster

**Pull request closed without merging**
