### PR TITLE
First commit 

### PR DESCRIPTION
**Pull request by Pierre-Alexandre35**
hi, this is the basic structure for the project

### CODE REVIEW

**Comment by harmanpreets1ngh** [comment]
LGTM

**Review by harmanpreets1ngh — COMMENTED** [review]
merging

**Comment by Pierre-Alexandre35** [comment]
ok thanks dude what are the 2 checks ?

**Comment by harmanpreets1ngh** [comment]
They were checking whether build passed or not. You should have committed the POM file and other elements of the basic structure for the project, you didn't do anything like that, hence it errored out. You can see the details of the checks by clicking on them.

**Comment by Luorinz** [comment]
Mark

**Pull request merged**
